# Generated by Django 5.2.5 on 2025-08-15 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_options_alter_basket_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='cover',
            field=models.ImageField(upload_to='media/banner_covers/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to='media/brand_logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(upload_to='media/product_covers/'),
        ),
    ]
